#
# Makefile for the lsi2esc GPIO extensions.
#

obj-$(CONFIG_LSI2ESC_MCP3208)	+= mcp3208-gpio.o
obj-$(CONFIG_LSI2ESC_MCP4922)	+= mcp4922-gpio.o
obj-$(CONFIG_LSI2ESC_RDAC_AIO)	+= rdac-aio.o
obj-$(CONFIG_LSI2ESC_RIMS_8051)	+= rims-8051.o
