#
# Makefile for the ioex devices
#

# Each configuration option enables a list of files.

obj-$(CONFIG_ECOREEX)		+= ecoreex.o
obj-$(CONFIG_BOARDSPEC)		+= boardspec.o
obj-$(CONFIG_PWMCLASS)		+= pwmd.o

