#
# Makefile for the misc classes
#

EXTRA_CFLAGS += -Iinclude/xenomai
obj-$(CONFIG_GPIOCLASS)		+= gpio.o
obj-$(CONFIG_PWMCLASS)		+= pwm.o
obj-$(CONFIG_SPICLASS)		+= spi.o
obj-$(CONFIG_LSI2ESC)		+= spi_interface.o
obj-y += rtdm/
obj-y += char/
obj-y += lsi2esc_devices/
